apiVersion: v1
kind: ConfigMap
metadata:
  name: osslm-ansible-rm
data:
{{- if .Values.app.config.env }}
{{ toYaml .Values.app.config.env | indent 2 }}
{{- end }}
  "LOG_LEVEL": {{ .Values.app.config.log.level }}
  "LOG_FOLDER": {{ .Values.app.config.log.dir }}
  "OS_CLIENT_CONFIG_FILE": {{ .Values.app.config.clientConfigFile }}
