{{- if .Values.app.config.kafka.useExisting }}
apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  ports:
  - name: broker
    port: 9092
    targetPort: kafka
  selector:
{{ toYaml .Values.app.config.kafka.existingSelectors | indent 4 }}
{{- end }}