name: osslm-ansible-resource-manager
version: 1.3.2
appVersion: 1.3.2
apiVersion: v1
description: A Helm chart for the osslm-ansible-resource-manager
# maintainers:
#- name:
#  email:
keywords:
- OSS
- LM
- OSSLM
- Resource Manager
- Ansible
- IBM
engine: gotpl
